package uk.co.strangeskies.reflection.codegen;

/**
 * This error should only ever be instantiated and thrown by the stub classes
 * generated by {@link ClassDeclaration class declarations}. Each method on a
 * stub implementation should throw this error and do nothing else. Such methods
 * should never be invoked.
 * 
 * @author Elias N Vasylenko
 */
public class StubInvocationError extends Error {
	private static final long serialVersionUID = 1L;

	public StubInvocationError() {
		this(new Exception().getStackTrace()[1]);
	}

	private StubInvocationError(StackTraceElement element) {
		super(
				"Method "
						+ element.getMethodName()
						+ " should not be invoked on stub class "
						+ element.getClassName());
	}
}
